### ISSUE TITLE
issues occured while reproducing GeneCompass

### ISSUE THREAD

**Issue by QingJun3** [xCompass-AI/GeneCompass#7]
Hello, I am trying to reproduce the GeneCompass paper you published, but I have encountered some issues during the process. 

As shown in the figure, the specific problem is that when I load the token_dictionary, I receive the error _pickle.UnpicklingError: invalid load key, 'v'. 

![image](https://github.com/user-attachments/assets/afb049e0-7ce1-4909-b4b3-3b1a7a37242a)

I would like to ask if you could provide some suggestions for how to resolve this issue, or possibly provide the environment image that you used during your runs.

**Comment by dinghaov587** [comment]
The author's LFS is over its data quota. Could you please help by sending me a copy? My email is [dingh2023@nanoctr.cn](mailto:dingh2023@nanoctr.cn). Thank you very much!

**Comment by wonwoo-0717** [comment]
I have the same request. The repository is over its data quota.  Could you please help by sending me  a pickle file. My email is bbxkkw@163.com  Thank you very much!!!

**Comment by chuiqin** [comment]
I have the same request.

**Comment by QingJun3** [comment]
I've been preparing for graduation recently, which is why I'm only replying now. It's been a long time since I reproduced GeneCompass, so I don't remember exactly which pickle file you needed. I've uploaded the prior_knowledge files from my directory to Google Drive, hoping they can help you. 

https://drive.google.com/drive/folders/1W8QWjZ4zWeHR9bDHpfSCtJwcY6DzLvz_?usp=sharing

@dinghaov587 @wonwoo-0717 @chuiqin @choushanyuan

**Comment by wonwoo-0717** [comment]
Thank you very much！！！

**Comment by chuiqin** [comment]
That’s very kind of you!​

**Comment by dinghaov587** [comment]
Thanks a lot！



---- Replied Message ----
| From | Chuiqin ***@***.***> |
| Date | 04/30/2025 17:40 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xCompass-AI/GeneCompass] issues occured while reproducing GeneCompass (Issue #7) |
chuiqin left a comment (xCompass-AI/GeneCompass#7)

That’s very kind of you!​
